### ISSUE TITLE
Support for generated classes in SCSS

### ISSUE THREAD

**Issue by alvaromartmart** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#46]
Would it be possible to support auto-completion of classes generated by SCSS as in this example?
```scss
$colors:(
    main: #FAEEBA,
    secondary: #FEAABE
)

@each $colorName, $colorValue in $colors {
  .text-#{$colorName}{
    color: $colorValue;
  }
}
```
This will generate classes `text-main`  and `text-secondary`, which the extension would need to cache and auto-complete.

Is this possible?
